### ISSUE TITLE
Is it easy to call this library by .f file instead of .F

### ISSUE THREAD

**Issue by edwardXZ06** [adtzlr/ttb#20]
Hi, many thanks for your efforts as I was trying to heavily use your library in the development of UMAT. However, due to software limitation, only the .f file is compatible with my current settings. I am wondering if it is easy to integrate your library by calling a .f file instead of .F file?

Thanks!

**Comment by adtzlr** [comment]
Hi @edwardXZ06,

yes this is possible. Just take an older version of this library (https://github.com/adtzlr/ttb/tree/15372e07ad2031a83b8e3a4fe1c99bf538c4d20b). I added the `.F` files because an Ansys-user had problems with the initial `.f` files.

Please note that there is one bug in this older version #18 but everything else is up-to-date.

Hope that helps!

**Comment by adtzlr** [comment]
Also thanks for letting me know that Abaqus has problems with `.F` files. I may provide two versions in the future, I'll see.

**Comment by edwardXZ06** [comment]
Hi. Thanks for your answer. 
The .F files work perfectly in Abaqus as far as I know. I am working on a open source finite element framework MOOSE, which has has developed an interface with Abaqus UMAT for material definition. 
Now the included .f file can be well found by the Abaqus interface, however I met a new issue shown as below.
![image](https://user-images.githubusercontent.com/88357649/130831438-0d0fce26-f291-4e43-88d5-9a57553e660c.png)
Since MOOSE is developed on C++, do you think this problem is caused by their fortran compiler?

**Comment by adtzlr** [comment]
@edwardXZ06 is it okay for you if I close this Issue? I think the titled issue regarding `.F` and `.f` files was solved.
